--- 
project: 
  key: DRAG
  plan: 
    key: SLAYER
    name: "Dragon Slayer Quest"
stages: 
  - 
    jobs: 
      - 
        artifacts: 
          - 
            name: "Red dragon's head"
            path: dragon/red/head
        requirements: 
          - isDragonLazy
        scripts: 
          - "echo 'Going to kill the red dragon, watch me'"
          - "sleep 1"
          - "echo 'Nailed it'"
        testParsers: 
          - 
            testResults: "**/mocha/*.json"
            type: mocha
          - 
            testResults: "**/junit/*.xml"
            type: junit
